version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - transf-scheduler

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    command: ["npm", "run", "serve"]
    networks:
      - transf-scheduler

networks:
  transf-scheduler:
    driver: bridge
